#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 AMD
# SPDX-License-Identifier: Apache-2.0
"""Derive a buildable coverage variant of verl's Dockerfile_rocm.ci.

Dockerfile_rocm.ci COPYs six files (Qwen3.5 training launchers, unit-test
runners, a fixture downloader and a test patch) from the build-context root.
None of them are present in the verl checkout, and none affect measured
coverage -- but a missing COPY source is a hard build failure, and the patch
RUN would fail even with an empty placeholder because `patch` rejects garbage
input under the Dockerfile's `set -e`.

Rather than fabricating stubs, drop exactly those instructions:

  1. every COPY whose source is absent from the build context, and
  2. every later RUN that references the destination path of such a COPY
     (this is what removes the `patch -p1 --forward` block).

Everything else is emitted byte-identically so Docker layer caching still
applies. Files that DO exist in the context are left alone, so dropping the
real ones in later makes them take effect again with no change here.
"""

from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path

# Flags that may precede the source operand of a COPY instruction.
_COPY_FLAG_PREFIX = "--"


def read_logical_lines(text: str) -> list[list[str]]:
    """Group physical lines into logical ones, honouring backslash continuations.

    A Dockerfile instruction can span many physical lines; dropping one means
    dropping all of them, so every group is kept intact for re-emission.
    """
    groups: list[list[str]] = []
    current: list[str] = []
    for line in text.splitlines(keepends=True):
        current.append(line)
        if not line.rstrip("\r\n").endswith("\\"):
            groups.append(current)
            current = []
    if current:
        groups.append(current)
    return groups


def instruction_of(group: list[str]) -> tuple[str, str]:
    """Return the (uppercased keyword, joined argument text) of a logical line."""
    joined = "".join(group)
    stripped = joined.strip()
    if not stripped or stripped.startswith("#"):
        return "", joined
    # Splice out the continuations so the arguments read as one line.
    flat = " ".join(
        part.rstrip("\r\n").rstrip("\\").strip() for part in group
    ).strip()
    keyword, _, rest = flat.partition(" ")
    return keyword.upper(), rest.strip()


def copy_operands(args: str) -> list[str]:
    """Split a COPY argument string into operands, discarding --flags."""
    try:
        tokens = shlex.split(args)
    except ValueError:
        tokens = args.split()
    return [t for t in tokens if not t.startswith(_COPY_FLAG_PREFIX)]


def derive(dockerfile: Path, context: Path) -> tuple[str, list[str]]:
    """Return the derived Dockerfile text and a human-readable list of drops."""
    groups = read_logical_lines(dockerfile.read_text())

    kept: list[str] = []
    dropped: list[str] = []
    missing_destinations: list[str] = []

    for group in groups:
        keyword, args = instruction_of(group)
        summary = next(
            (line.strip() for line in group if line.strip()), ""
        )

        if keyword == "COPY":
            operands = copy_operands(args)
            if len(operands) >= 2:
                source, destination = operands[0], operands[-1]
                if not (context / source).exists():
                    missing_destinations.append(destination)
                    dropped.append(f"COPY (source absent: {source}) -- {summary}")
                    continue

        if keyword == "RUN" and missing_destinations:
            referenced = [d for d in missing_destinations if d in args]
            if referenced:
                dropped.append(
                    f"RUN (references dropped {', '.join(referenced)}) -- {summary}"
                )
                continue

        kept.extend(group)

    return "".join(kept), dropped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dockerfile", required=True, type=Path)
    parser.add_argument(
        "--context",
        required=True,
        type=Path,
        help="Build context the COPY sources are resolved against.",
    )
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    if not args.dockerfile.is_file():
        print(f"ERROR: dockerfile not found: {args.dockerfile}", file=sys.stderr)
        return 1
    if not args.context.is_dir():
        print(f"ERROR: context not a directory: {args.context}", file=sys.stderr)
        return 1

    text, dropped = derive(args.dockerfile, args.context)

    header = (
        "# GENERATED by rocm-coverage/derive_base_dockerfile.py -- DO NOT EDIT.\n"
        f"# Source: {args.dockerfile}\n"
        f"# Context: {args.context}\n"
        "#\n"
        "# Instructions whose COPY sources are absent from the build context have\n"
        "# been dropped (see the run log for the list). They are training launchers,\n"
        "# unit-test runners and a test patch -- none contribute measured coverage.\n"
        "# Every remaining instruction is byte-identical to the source, so Docker\n"
        "# layer caching still applies.\n"
        "#\n"
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header + text)

    if dropped:
        print(f"Dropped {len(dropped)} instruction(s) from {args.dockerfile.name}:")
        for entry in dropped:
            print(f"  - {entry}")
    else:
        print(f"No instructions dropped; {args.output.name} matches the source.")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
